### ISSUE TITLE
Use `email.message.Message` instead of rolling own (`RFC822Message`)

### ISSUE THREAD

**Issue by dnicolodi** [pypa/pyproject-metadata#101]
`pyproject-metadata` currently rolls his own serialization of the metadata. The specification says that the metadata serialization format is what is understood by the `email.parser` module when using the `compat32` policy. I think it would therefore be easier and safer to simply use the `email.message` module to serialize the metadata.

I started working on this but I was sidetracked by the fact that `email.message.Message` is now described as "legacy" and `email.message.EmailMessage` did not work for me when using the `compat32` policy. I see that @henryiii is putting some work in this package (thanks!!) thus I just wanted to contribute this thought.

**Comment by pradyunsg** [comment]
The metadata parsed by this project is not a METADATA file (i.e. https://packaging.python.org/specifications/core-metadata/) but rather project metadata (https://packaging.python.org/en/latest/specifications/pyproject-toml/#pyproject-project-table).

These are not equivalent and, thus don't really have a 1:1 mapping. If we do want to implement this in a different form, it would actually be better to move over to using https://packaging.pypa.io/en/stable/metadata.html for that (or helping that project decide on the PEP 621 implementation story).

**Comment by dnicolodi** [comment]
@pradyunsg I didn't write that this project parses package METADATA files. I wrote that this project serializes package metadata into package METADATA, which is exactly what the `StandardMetadata.as_rfc822() ` method does https://github.com/pypa/pyproject-metadata/blob/14c9660fcc54d5e087dd76612905739abe731f13/pyproject_metadata/__init__.py#L279 Therefore I don't understand the first half of your objection.

`packaging` has API to parse METADATA files, however, AFAIK there is not public API to serialize them, which is what `pyproject-metadata` is concerned with. Therefore, I don't understand the second half of your objection either.

**Comment by pradyunsg** [comment]
Ah, I was being confused by your use of serialise here. Language is tricky.

I understand what you're suggesting now, and this make sense to me.

> AFAIK there is not public API to serialize them

There is? https://packaging.pypa.io/en/stable/metadata.html#usage shows how it can be used as well, with `RawMetadata` being literally a typed dictionary.

That said, RFC822Message -> [email.message.Message](https://docs.python.org/3/library/email.compat32-message.html#email.message.Message) seems reasonable to me.

**Comment by henryiii** [comment]
I've played with this a bit, and got stuck on the body. The easiest transition would be to use `EmailMessage` as a base class for RFC822Message, and see what the differences are. So far:

* `__str__` isn't supported, but easy to use `bytes(m).decode("utf-8")`.
* `__setitem__` doesn't support skipping `None` values
* `.headers` is pretty easy to generate from `.items()`, just needs automatic joining of lists
* I don't know how to set and get a plain body with `EMailMessage`.

Also ordering is different, indentation is different, and wrapping is different, but those I think are fine to adjust the tests to. I'm mostly stuck on not knowing how to handle message bodies.

**Comment by frostming** [comment]
I don't think this will happen in 0.8.0, right? Are there any remaining issues with the release of 0.8.0 now?

**Comment by henryiii** [comment]
I think it’s ready as far as I’m conserved. No, this is just (potential) cleanup.
