### ISSUE TITLE
Type annotation for the `StandardMetadata.from_pyproject()` not sublcass friendly

### ISSUE THREAD

**Issue by dnicolodi** [pypa/pyproject-metadata#107]
The type annotation as currently written requires subclasses of `StandardMetadata` wishing to override the `from_pyproject()` method to ignore typing.

**Comment by dnicolodi** [comment]
I'm definitely not a typing expert, but it seems that to fix this the `Self` type annotation introduced in Python 3.11 is needed. I'm not sure that adding a test dependency on `typing-extensions` just for this is worth.

**Comment by henryiii** [comment]
If TYPE_CHECKING with future annotations is fine.v

**Comment by dnicolodi** [comment]
Sure, but should I still add the `typing-extensions` dependency in `project.optional-dependencies.test` for `python_version<"3.11"`?

**Comment by henryiii** [comment]
No, I’d add it for typing (even though it’s not technically needed, type checkers already include it) if we have that somewhere.

**Comment by henryiii** [comment]
Oh, it’s here: https://github.com/pypa/pyproject-metadata/blob/04d4cf01eabc03001b5255cb2befae1537903d1a/noxfile.py#L15

I’d not bother to add it then I think. Mypy will have it v
