### ISSUE TITLE
StandardMetadata.{authors,maintainers} can contain None for email despite declared type of str

### ISSUE THREAD

**Issue by diazona** [pypa/pyproject-metadata#126]
While working on [an issue in a project of mine](https://github.com/diazona/setuptools-pyproject-migration/issues/135) that uses pyproject-metadata, I noticed that `StandardMetadata.from_pyproject()` is returning `None` in place of a missing author or maintainer email, which violates the declared type of that field, `list[tuple[str, str]]`. As a simple example:

```pycon
>>> from pyproject_metadata import StandardMetadata
>>> metadata = {"project": {"name": "shrubbery", "version": "0", "authors": [{"name": "Monty Python"}]}}
>>> StandardMetadata.from_pyproject(metadata).authors
[('Monty Python', None)]
```

Is the type constraint on the field supposed to be different (likely `list[tuple[str | None, str | None]]`), or should `DataFetcher.get_people()` be modified to use a dummy string when no email address is present? (Or is there something more going on that I'm missing?)

**Comment by henryiii** [comment]
I expect this is just a bug in the declared types.

**Comment by henryiii** [comment]
The name gets translated to "Unknown", actually, if missing. Not fond of injecting an word like that - assumes English, can't be handled if someone really did want that to be their name, etc.

**Comment by diazona** [comment]
Oh true, yeah the "Unknown" thing is annoying. I wonder if it might be related to the fact that setuptools used to use "UNKNOWN" to represent missing metadata values, but then again it's title case in this project whereas setuptools used uppercase :shrug: And in any case, version 62.2 of setuptools switched to using `None` instead. Anyway, in my project we worked around the issue in setuptools by replacing `"UNKNOWN"` with `""`; I suppose we could work around this the same way. But that's technically a separate issue.

Thanks for working on this :smile:
