### ISSUE TITLE
`pyproject_metadata.StandardMetadata()` constructor wants `pathlib.Path` for `license_files`

### ISSUE THREAD

**Issue by dnicolodi** [pypa/pyproject-metadata#204]
This is not a problem in itself, but `pyproject_metadata.from_pyproject()` uses a regular string for the `project_dir` argument. Maybe both strings and `pathlib.Path` objects should be accepted for consistency in the API?

**Comment by henryiii** [comment]
I see:

https://github.com/pypa/pyproject-metadata/blob/49fd43fdefeb6d8427a6e3d10dfa959a049a6a19/pyproject_metadata/__init__.py#L298

And:

https://github.com/pypa/pyproject-metadata/blob/49fd43fdefeb6d8427a6e3d10dfa959a049a6a19/pyproject_metadata/__init__.py#L323

So it should already be supported, I think?

**Comment by henryiii** [comment]
Ahh, I didn't really look at the title, sorry. There's no way to do this with dataclasses, they don't support conversions. `attrs` does, but this was considered too advanced for the stdlib. We can control `.from_pyproject`, but directly using the constructor requires the correct types.

**Comment by henryiii** [comment]
We can, though unless we go over every single field, it's a bit arbitrary, and then would we also then want to verify no one sets it later with a string?

Your type checker should be able to catch this, though, which is probably why I'd never worried about it.

**Comment by dnicolodi** [comment]
Thinking about it, I don't see why this needs special treatment, indeed.
