### ISSUE TITLE
Validate classifiers

### ISSUE THREAD

**Issue by FFY00** [pypa/pyproject-metadata#46]

**Comment by henryiii** [comment]
I'd much rather just have some docs on how to validate with `classifiers`. I'd prefer not to have a mandatory dependency, and don't want to vendor and have to keep updating, and if the build backend, etc. want to do this, they can decide how they want to include `classifiers`.

**Comment by henryiii** [comment]
## Classifier validation

You can easily validate the classifiers using the PyPI package `trove_classifiers`, which is the canonical source of trove classifier info.

```python
import trove_classifiers

invalid_classifiers = set(metadata.classifiers) - trove_classifiers.classifiers

# Also the deprecated dict if you want it
dep_names = set(metadata.classifiers) & set(trove_classifiers.deprecated_classifiers)
deprecated_classifiers = {k: trove_classifiers.deprecated_classifiers[k] for k in dep_names)
```
