### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by henryiii** [pypa/pyproject-metadata#90]
With the recent move to the PyPA, I was expecting this to be `pypa/pyproject-metadata`, not `pypa/python-pyproject-metadata`. PyPA already implies Python, and `pyproject` also has `py` for Python, meaning Python is repeated 2-3 times. It's also not the name of the project - the package name is `pyproject-metadata`, and I'd like to have `pyproject-metadata.pypi.io` for the docs (I don't have permissions for docs or PyPI), so it seems like `pyproject-metadata` would be a better repo name.

**Comment by henryiii** [comment]
Also, pre-commit needs to be reactivated.

**Comment by pradyunsg** [comment]
If one of the maintainers (@pypa/pyproject-hooks-committers) gives me the an OK to do this, I can click all the buttons to rename this repo and enable pre-commit.

**Comment by pfmoore** [comment]
I have no idea why I am listed as a committer here - I'm happy for this to be done, though, for what it's worth. Shouldn't @FFY00 be the owner? And shouldn't the committer list have been transferred when the project was moved into the PyPA?

**Comment by pfmoore** [comment]
@henryiii is a maintainer, so I'm not clear why he can't do this himself.

**Comment by henryiii** [comment]
I don't have the "settings" tab. And I can't add a repo to pre-commit; only someone with permissions to all repositories can change the allowed repositories. When I've done it in the past (I think for cibuildwheel, actually), adding a repo caused every repo I didn't have permissions for to be removed from pre-commit. (Maybe that's been fixed? But not risking it again).

**Comment by pfmoore** [comment]
Weird. I've renamed it (I do have "settings" here, no idea why) on the basis that as you're a committer, your approval will do 🙂

**Comment by pfmoore** [comment]
Looking at the "Collaborators and teams" tab in settings, there's 4 teams that probably need renaming (I don't see a "rename" button, so it might be delete and recreate). I'll leave that to the actual owners of this project (@FFY00 and @di) to sort out.

**Comment by henryiii** [comment]
Do we also have pre-commit.ci enabled yet? I don't see it in the current list:

```
 pypa/auditwheel
 pypa/bandersnatch
 pypa/build
 pypa/cibuildwheel
 pypa/gh-action-pypi-publish
 pypa/installer
 pypa/packaging.python.org
 pypa/pip
 pypa/pipx
 pypa/setuptools_scm
 pypa/virtualenv
 pypa/wheel
```

**Comment by pfmoore** [comment]
I don’t know how to do that and I’d prefer to let a project owner do it anyway.

**Comment by henryiii** [comment]
@pradyunsg could you add pre-commit?

**Comment by henryiii** [comment]
Thanks whoever added it! :)
