### ISSUE TITLE
Project teams on Github

### ISSUE THREAD

**Issue by FFY00** [pypa/pyproject-metadata#92]
It seems Github changed something, and I am no longer able to administer teams being a project administrator. I am assuming this is due to some change on Github's part, since I checked with the pypa/build teams and I am getting the same result as in pyproject-metadata teams. Previously I was able to manage team members.

@di or @pradyunsg, could you add the following users to the pypa/python-pyproject-metadata-committers team?
- henryiii
- rgommers
- frostming

**Comment by di** [comment]
@FFY00 I've invited those folks to that team and also made you a maintainer of all teams for this project as well, so you should be able to make changes in the future.
